# Generated by Django 5.0.1 on 2024-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('company', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=25)),
                ('skills', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
